config/routes.rb
Corners::Application.routes.draw do
  get "corner/index"
  get "corner/initiatives"
  get "corner/overview"
  get "corner/members"
  get "corner/work2011"
  get "corner/work2010"
  get "corner/event2010"
  get "corner/event2011"
  get "corner/event2012"
  get "corner/whygive"
  get "corner/sponsors"
  get "corner/makedonation"
  get "corner/eval"

  root to: 'corner#index'
  get "home/index"
  get "home/overview"
  get "home/members"
  get "home/initiatives"
  get "home/work2011"
  get "home/work2010"
  get "home/event2010"
  get "home/event2011"
  get "home/event2012"
  get "home/whygive"
  get "home/sponsors2010"
  get "home/makedonation"
  get "home/eval"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/corner_controller.rb
class CornerController < ApplicationController
  def index
  end

  def overview
  end

  def members
  end

  def initiatives
  end

  def work2011
  end

  def work2010
  end
  
  def event2010
  end
  
  def event2011
  end
  
  def whygive
  end
  
  def sponsors
  end
  
  def makedonation
  end
  
  def eval
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def overview
  end
  
  def members
  end
  
  def initiatives
  end
  
  def work2011
  end

  def work2010
  end
  
  def event2010
  end
  
  def event2011
  end
  
  def whygive
  end
  
  def sponsors2010
  end
  
  def makedonation
  end
  
  def eval
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def assetURL (loc)
		'http://corners_assets.s3.amazonaws.com/images/'+loc
	end
end

app/helpers/corner_helper.rb
module CornerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/corner/_db.html.erb
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="WMUFGCNAY9WU2">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

app/views/corner/_navbar.html.haml
.navbar{class: "navbar-fixed-top"}
	.navbar-inner
		.container
			%a.btn-navbar{class: "btn", "data-toggle"=>"collapse", "data-target"=>".nav-collapse"}
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			%a.brand{href: root_path}
				The Corners Society
			.nav-collapse{class: "collapse"}
				%ul.nav{class: "pull-right"}
					%li.dropdown
						%a.dropdown-toggle{"data-toggle"=>"dropdown"}
							About Us
							%b.caret
						%ul.dropdown-menu
							%li
								%a{href: corner_overview_path} Overview
							%li
								%a{href: corner_members_path} Members
					%li.dropdown
						%a.dropdown-toggle{"data-toggle"=>"dropdown"}
							Goals
							%b.caret
						%ul.dropdown-menu
							%li
								%a{href: corner_initiatives_path} Initiatives
					%li.dropdown
						%a.dropdown-toggle{"data-toggle"=>"dropdown"}
							Our Work
							%b.caret
						%ul.dropdown-menu
							%li
								%a{href: corner_work2011_path} 2011
							%li
								%a{href: corner_work2010_path} 2010
					%li.dropdown
						%a.dropdown-toggle{"data-toggle"=>"dropdown"}
							Events
							%b.caret
						%ul.dropdown-menu
							%li
								%a{href: corner_event2012_path} 2012
							%li
								%a{href: corner_event2011_path} 2011
							%li
								%a{href: corner_event2010_path} 2010
					%li.dropdown
						%a.dropdown-toggle{"data-toggle"=>"dropdown"}
							Donations
							%b.caret
						%ul.dropdown-menu
							%li
								%a{href: corner_whygive_path} Why Give?
							%li
								%a{href: corner_sponsors_path} Sponsors
							%li
								%a{href: corner_makedonation_path} Make a Donation

app/views/corner/_navbarBottom.html.haml
.navbar{class: "navbar navbar-fixed-bottom"}
	.navbar-inner
		.container
			%h6
				%small Founded by dedicated Charlotte citizens, The Corners Society serves the community through reverence for the past and charity for the future.
				%a{:href => "mailto:info@thecornerssociety.org?Subject=Web%20Contact"}email us

app/views/corner/_tabreadyjs.html.erb
<script type="text/javascript">
$(document).ready(function() {
	$('#myTab a').click(function (e) {
  		e.preventDefault();
  		$(this).tab('show');
	}); 
	$('#myTab a:first').tab('show'); 
});

</script>

app/views/corner/event2010.html.haml
.row
	.span12
		.page-header
			%h1
				2010 Annual Gala
.row
	.span12
		#myCarousel{class:"carousel"}
			.carousel-inner
				.active{class: "item"}
					.thumbnail
						= image_tag assetURL('invitationii.png')
				.item
					.thumbnail
						= image_tag assetURL('gala_0.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala_1.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala_2.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala_3.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala_4.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala_5.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala_6.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala_7.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala_8.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala_9.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala_10.jpg')
			%a.carousel-control{class: "left", href:"#myCarousel", "data-slide"=>"prev"} &lsaquo;
			%a.carousel-control{class: "right", href:"#myCarousel", "data-slide"=>"next"} &rsaquo;

app/views/corner/event2011.html.haml
.row
	.span12
		.page-header
			%h1
				Annual Barbeque 2011
.row
	.span12
		%p &nbsp;&nbsp;&nbsp;&nbsp;In November, the Corners Society hosted a "Backyard BBQ" at the home of Sean and Kristin Hair. Prior to the event the corners society purchased overnight bags as well as basic toiletries to address a need at the men's shelter for members of the SABER program - an adult support group for recovering substance abusers ... During the event members packed the bags with the toiletries and later delivered them to the shelter.
.row
	.span12
		.thumbnail
			=image_tag assetURL('bbq_2011.png')

app/views/corner/event2012.html.haml
.row
	.span12
		.page-header
			%h1
				2012 Annual Gala
.row
	.span12
		#myCarousel{class:"carousel"}
			.carousel-inner
				.active{class: "item"}
					.thumbnail
						= image_tag assetURL('gala/0001.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0004.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0012.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0017.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0016.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0019.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0025.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0027.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0035.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0050.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0053.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0056.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0061.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0065.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0071.jpg')
				.item
					.thumbnail
						= image_tag assetURL('gala/0072.jpg')
			%a.carousel-control{class: "left", href:"#myCarousel", "data-slide"=>"prev"} &lsaquo;
			%a.carousel-control{class:"right", href:"#myCarousel", "data-slide"=>"next"} &rsaquo;

app/views/corner/index.html.haml
.row
	.span12
		%ul.thumbnails
			%li.span12
				.thumbnail
					=image_tag( assetURL("cornerssociety.gif"), alt: "corners logo")
			%li.span12
				%h1
					%small The Corners Society is where the people of Charlotte can help their neighbors in need. Through a commitment to direct participation in volunteer efforts, The Corners Society has the unique capability of identifying where resources are needed in our community and responding to those needs in a way that produces the greatest impact.
			%li.span12
				.thumbnail
					=image_tag(assetURL("charlotteSkyline.jpg"), alt: "charlotte NC")

app/views/corner/initiatives.html.haml
.row
	.span12
		.page-header
			%h1
				Initiatives
.row
	.span6
		%p &nbsp;&nbsp;&nbsp;&nbsp;Due to its complex nature as well as its broad and indiscriminate effects, the current recession can be particularly devastating to many citizens. In attempting to alleviate the burden on the City of Charlotte, it is necessary to approach the issue from multiple perspectives.

		%h3	Charitable Needs
		%p &nbsp;&nbsp;&nbsp;&nbsp;During the creation of The Corners Society in 2009, it was unanimously agreed upon that the present economic crisis and its direct impact on the citizens of Charlotte must be the focus of our immediate efforts. The “Great Recession” is a world wide issue, but its effects are most intensely felt at the community level. Charlotte is no exception.

		%h3 Volunteering
		%p &nbsp;&nbsp;&nbsp;&nbsp;By actually getting into the community and physically assisting Target Charities, The Corners Society helps to alleviate that over-stressed social infrastructure that frequently has limited personnel and financial resources.
	.span6
		.thumbnail
			= image_tag assetURL('IMG_0514.jpg'), alt: "Working in field"
.row
	.span12
		%h3 Investment in the Future
		%p &nbsp;&nbsp;&nbsp;&nbsp;The Corners Society invests in the future generations of Charlotte by contributing resources to Target Charities that focus on maintaining and improving the quality of life within the community.

		%h3 Direct Donation
		%p &nbsp;&nbsp;&nbsp;&nbsp;By giving money directly to our carefully selected Target Charities, The Corners Society is ensuring that our philanthropic efforts will have the greatest impact in the community and on those citizens over-burdened by the current economic hardship.

app/views/corner/makedonation.html.haml
.row
	.span12
		.page-header
			%h1
				Make a Donation
.row
	.span12
		.span5{class: "offset4"}
			= link_to("Click Here to See Sponsorship Levels", asset_path("CornersSponsorshipTiers.pdf"))
.row
	.span12
		.span2{class: "offset5"}
			= render partial: "db"
.row
	.span12
		.span5{class: "offset4"}
			%p The Corners Society is recognized by the IRS as a 501(c)(3) organization. <a href="http://corners_assets.s3.amazonaws.com/images/501c3_corners.pdf">501(c)(3) letter</a>

app/views/corner/members.html.haml
.row
	.span12
		.page-header
			%h1
				Members
.row
	.span5{class: "offset5"}
		%h1 Board of Directors
.row
	.span4{class: "offset3"}
		%dl
			%dt
				Matthew F. McLanahan
			%dd
				Chairman
	.span4
		%dl	
			%dt
				T. Heath Norman
			%dd
				Service Director
.row
	.span3{class: "offset2"}
		%dl
			%dt
				Timothy A. Broderick
			%dd
				Secretary
	.span3
		%dl
			%dt
				Andrew F. Dana
			%dd
				General Counsel
	.span3
		%dl
			%dt
				Jonathan D. Dixon
			%dd
				Treasurer
.row
	.span4{class: "offset5"}
		%h1 Membership
.row
	.span3{class: "offset2"}
		%ul.unstyled
			%li C. Yeatts Anderson
			%li Matthew P. Cochrane	 
			%li John D. Comly
			%li Oliver R. Cross III	
			%li Brett H. Estwanik	 
			%li Mark. L. Griffith
			%li Ransome Foose
			%li Brannen Edge
	.span3
		%ul.unstyled
			%li Sean R. Hair	
			%li Guy T. McBride III	
			%li R. Neal Porter
			%li James W. Roberts	
			%li Eric J. Speckman	 
			%li Garrik L. Sturges
			%li Jay Levell
	.span3
		%ul.unstyled
			%li James D. Thompson IV	
			%li Christopher S. Walker	
			%li W. Stewart Cowden III
			%li Alan C. Welch Jr.	
			%li Erik B. Johnson
			%li John Hallett
			%li Dunn Mileham

app/views/corner/overview.html.haml
.row
	.span12
		.page-header
			%h1
				Overview
.row
	.span12
		%p At its foundation, The Corners Society is dedicated to honoring the City of Charlotte through philanthropic, civic, and charitable action. In this community that has given so much, The Corners Society works to give back.
		%p The Corners Society operates through a high level of community involvement and hands-on volunteer work in an effort to carry out the following:
.row
	.span10{class: "offset1"}
		%ul
			%li Identification of charities (Target Charities) that are in the greatest need of immediate assistance.
			%li Directly volunteering within Target Charities for specific projects that respond to the needs of the City of Charlotte and surrounding area.
			%li Donation of necessary goods or services that address shortages on the community level as well as the individual charity or organization level.
			%li Financial support of Target Charities that directly impact the Charlotte community by addressing the City’s primary philanthropic needs.
.row
	.span12
		%p Through a commitment to direct involvement in charitable projects, The Corners Society advantage lies in its ability to allocate financial resources in conjunction with direct volunteer involvement in an effort to produce the most significant positive impact to our community and its citizens.
.row
	.span12
		%ul.thumbnails
			%li.span6
				.thumbnail
					= image_tag assetURL('Socks.png'), :alt => 'Urban Ministry'
			%li.span6
				.thumbnail
					= image_tag assetURL('hab_9.jpg'), :alt => 'Habitat For Humanity'
		 

app/views/corner/work2010.html.haml
.row
	.span12
		.page-header
			%h1
				Our Work 2010
.row
	.span12
		%ul.nav{class: "nav-tabs", id: "myTab"}
			%li.active
				%a{href: "#Habitat", "data-toggle"=>"tab"} Habitat For Humanity
			%li
				%a{href: "#Urban", "data-toggle"=>"tab"} Urban Ministry
			%li
				%a{href: "#Levine", "data-toggle"=>"tab"} Levine Hospital
		.tab-content
			.tab-pane{class: "active", id: "Habitat"} 
				%p &nbsp;&nbsp;&nbsp;The members of The Corners Society joined Habitat for Humanity to literally put a roof over the head of Glinh Romah and Yup Rolan in Southwest Charlotte. Starting out early one Saturday morning in July, the members nailed (and sometimes re-nailed) together an entire roof while working alongside Mr. Glinh Romah and Mr. Yup Rolan, the future owners. In the end, the day was a complete success. All of the members had a great time, no one fell off of the roof, and an important project was completed in the creation of a home for a member of the community.
				#myCarousel{class:"carousel"}
					.carousel-inner
						.active{class: "item"}
							.thumbnail
								= image_tag assetURL('hab_1.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hab_2.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hab_3.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hab_4.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hab_5.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hab_6.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hab_7.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hab_8.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hab_9.jpg')
					%a.carousel-control{class: "left", href:"#myCarousel", "data-slide"=>"prev"} &lsaquo;
					%a.carousel-control{class:"right", href:"#myCarousel", "data-slide"=>"next"} &rsaquo;
			.tab-pane{id:"Urban"} 
				%p &nbsp;&nbsp;&nbsp;The Urban Ministry Center in Charlotte, NC is dedicated to serving our homeless neighbors in an effort end homelessness through a variety of initiatives. The Corners Society spent the day in the Urban Ministry gardens weeding, clearing, and aerating the plots, so that the neighbors could come back in to plant the next round of flowers, fruits, and vegetables, all of which will be used by the Urban Ministry. 
				%p &nbsp;&nbsp;&nbsp;While volunteering, we learned that the greatest material need for the neighbors at Urban Ministry is socks. In response, the Corners Society has donated 1,000+/- pairs of socks to the organization to give out, as needed
				#myCarousel2{class:"carousel"}
					.carousel-inner
						.active{class: "item"}
							.thumbnail
								= image_tag assetURL('IMG_0495.jpg')
						.item
							.thumbnail
								= image_tag assetURL('IMG_0496.jpg')
						.item
							.thumbnail
								= image_tag assetURL('IMG_0497.jpg')
						.item
							.thumbnail
								= image_tag assetURL('IMG_0498.jpg')
						.item
							.thumbnail
								= image_tag assetURL('IMG_0499.jpg')
						.item
							.thumbnail
								= image_tag assetURL('IMG_0500.jpg')
						.item
							.thumbnail
								= image_tag assetURL('IMG_0501.jpg')
						.item
							.thumbnail
								= image_tag assetURL('IMG_0502.jpg')
						.item
							.thumbnail
								= image_tag assetURL('IMG_0503.jpg')
						.item
							.thumbnail
								= image_tag assetURL('IMG_0505.jpg')
					%a.carousel-control{class:"left", href:"#myCarousel2", "data-slide"=>"prev"} &lsaquo;
					%a.carousel-control{class:"right", href:"#myCarousel2", "data-slide"=>"next"} &rsaquo;
			.tab-pane{id:"Levine"} 
				%p &nbsp;&nbsp;&nbsp;A premier fundraising event for Levine Children’s Hospital, the Hopebuilders 5K Run/Walk , now in its 15th year and attracts supporters of all kinds. Last October The Corners Society hosted and helped run “the kids amazing race” during the 5k and also made a general donation to the Levine Children’s Hospital.
				#myCarousel3{class:"carousel"}
					.carousel-inner
						.active{class: "item"}
							.thumbnail
								= image_tag assetURL('hope_0.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hope_1.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hope_2.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hope_3.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hope_4.jpg')
						.item
							.thumbnail
								= image_tag assetURL('hope_5.jpg')
					%a.carousel-control{class:"left", href:"#myCarousel3", "data-slide"=>"prev"} &lsaquo;
					%a.carousel-control{class:"right", href:"#myCarousel3", "data-slide"=>"next"} &rsaquo;
= render partial: "tabreadyjs"

app/views/home/_footer.html.haml
#footer
  .blurb Founded by dedicated Charlotte citizens, The Corners Society serves the community through reverence for the past and charity for the future.
  %a{:href => "mailto:info@thecornerssociety.org?Subject=Web%20Contact"}email us

app/views/home/_gimpTop.html.haml
#topTable
  = image_tag("T_CornersTopTable.png", id:"mainTop")
  #aboutUs{class:"topNav"}
    = image_tag("T_AboutUs.png")
    #aboutUsTable{class:"navDropDown"}
      %table
        %tr
          %td
            = link_to "Overview", home_overview_path
        %tr
          %td
            = link_to "Members", home_members_path
  #goals{class:"topNav"}
    = image_tag("T_Goals.png", class:"topNav")
    #goalsTable{class:"navDropDown"}
      %table
        %tr
          %td
            = link_to "Initiatives", home_initiatives_path
  #ourWork{class:"topNav"}
    = image_tag("T_OurWork.png", class:"topNav")
    #ourWorkTable{class:"navDropDown"}
      %table
        %tr
          %td
            = link_to "2011", home_work2011_path
        %tr
          %td
            = link_to "2010", home_work2010_path
  #events{class:"topNav"}
    = image_tag("T_Events.png", class:"topNav")
    #eventsTable{class:"navDropDown"}
      %table
        %tr
          %td
            = link_to "2012", home_event2012_path
        %tr
          %td
            = link_to "2011", home_event2011_path	
        %tr
          %td
            = link_to "2010", home_event2010_path
  #donations{class:"topNav"}
    = image_tag("T_Donations.png", class:"topNav")
    #donationsTable{class:"navDropDown"}
      %table
        %tr
          %td
            = link_to "Why Give?", home_whygive_path
        %tr
          %td
            = link_to "2010 Sponsors", home_sponsors2010_path
        %tr
          %td
            = link_to "Make a Donation", home_makedonation_path

app/views/home/_ie.html.erb
<!--[if gte IE 6]>
<style>
.topPanes p{
font-size:80% ! important;
}
#DropDowns{
	top: 0px;
}
#dropDownTable {
font-size: 98%;
}
#goals_initiatives {
color: #444;
font-size: 90%;
line-height: 18px;
}
#membersTable tr td{
	text-align:center;
	padding-left:10px;
	padding-right:10px;
}
.homepageImages{
	position: fixed;
	top: 310px;
}
</style>
<![endif]-->

app/views/home/_top.html.haml
#top
	%table{id:"logoTable"}
		%tr
			%td
				= link_to image_tag("corner_logo.png", id:"cornersLogo"), root_path
			%td
				%a{href: root_path}
					%span{class:"titleFont"}
						The Corners Society
				%br
				%span{id:"lowerTitleFont"}
					Veneratio Per Caritatem
	#DropDowns
		%table{id:"dropDownTable"}
			%tr
				%td
					%span
						About Us
					%table
						%tr
							%td
								= link_to "Overview", home_overview_path
						%tr
							%td
								= link_to "Members", home_members_path
				%td
					%span
						Goals
					%table
						%tr
							%td
								= link_to "Initiatives", home_initiatives_path
				%td
					%span
						Our Work
					%table
						%tr
							%td
								= link_to "2011", home_work2011_path
						%tr
							%td
								= link_to "2010", home_work2010_path
				%td
					%span
						Events
					%table
						%tr
							%td
								= link_to "2012", home_event2012_path
						%tr
							%td
								= link_to "2011", home_event2011_path	
						%tr
							%td
								= link_to "2010", home_event2010_path
				%td
					%span
						Donations
					%table
						%tr
							%td
								= link_to "Why Give?", home_whygive_path
						%tr
							%td
								= link_to "2010 Sponsors", home_sponsors2010_path
						%tr
							%td
								= link_to "Make a Donation", home_makedonation_path

app/views/home/event2011.html.haml
= render partial:"ie"
/= stylesheet_link_tag "gimpTop"
/= render partial:"top"
/#mainContainer
#mainC{style:"height: 1150px;"}
	= render partial: "gimpTop"
	#pageTitle
		%h1
			Annual BBQ 2011
		%br
		.bbq
			=image_tag 'bbq_2011.png'
		.eventSubText
			%p
				In November, the Corners Society hosted a "Backyard BBQ" at the home of Sean and Kristin Hair. Prior to the event the corners society purchased overnight bags as well as basic toiletries to address a need at the men's shelter for members of the SABER program - an adult support group for recovering substance abusers ... During the event members packed the bags with the toiletries and later delivered them to the shelter.

= render partial:"footer"

app/views/home/index.html.haml
/= stylesheet_link_tag "gimpTop"
#mainC
  = render partial:"gimpTop"
  #middle
    = image_tag("INDEX_middleIndex.png", id:"middleImage")
    = render partial:"footer"

app/views/home/indexBACKUP.html.haml
= render partial:"ie"
#homePage
	%table{id:"logoTable"}
		%tr
			%td
				= image_tag("corner_logo.png", id:"cornersLogo")
			%td
				%a{href: home_overview_path}
					%span{class:"titleFont"}
						&nbsp;&nbsp;The Corners Society
				%table
					%tr
						%td
							%a{href: home_overview_path}
								%span{id:"lowerTitleFontHomePage"}
									Veneratio Per Caritatem
		%tr
			%td
			%td
				#DropDownsHomepage
					%table{id:"dropDownTable"}
						%tr
							%td
								%span
									About Us
								%table
									%tr
										%td
											= link_to "Overview", home_overview_path
									%tr
										%td
											= link_to "Members", home_members_path
							%td
								%span
									Goals
								%table
									%tr
										%td
											= link_to "Initiatives", home_initiatives_path
							%td
								%span
									Our Work
								%table
									%tr
										%td
											= link_to "2011", home_work2011_path
									%tr
										%td
											= link_to "2010", home_work2010_path
							%td
								%span
									Events
								%table
									%tr
										%td
											= link_to "2012", home_event2012_path
									%tr
										%td
											= link_to "2011", home_event2011_path	
									%tr
										%td
											= link_to "2010", home_event2010_path
							%td
								%span
									Donations
								%table
									%tr
										%td
											= link_to "Why Give?", home_whygive_path
									%tr
										%td
											= link_to "2010 Sponsors", home_sponsors2010_path
									%tr
										%td
											= link_to "Make a Donation", home_makedonation_path
	.homepageImages
		= image_tag("charlotteSkyline.jpg", id:"home3")
//%img{src:"assets/charlotteSkyline.jpg", id:"home3", class:"homeImages"}
//#mainContainer
//%img{src:"assets/home1.jpg", id:"home1", class:"homeImages"}
//%img{src:"assets/home2.jpg", id:"home2", class:"homeImages"}
//%img{src:"assets/charlotteSkyline.jpg", id:"home3", class:"homeImages"}
//%img{src:"assets/home3.jpg", id:"home3", class:"homeImages"}
/= render partial:"footer"

app/views/home/initiatives.html.haml
= render partial:"ie"
/= render partial:"top"
/= stylesheet_link_tag "gimpTop"
/#mainContainer
#mainC
  = render partial:"gimpTop"
  #pageTitle
    %h1
      Initiatives
  #goals_initiatives
    = image_tag 'IMG_0514.jpg'

    %p &nbsp;&nbsp;&nbsp;&nbsp;Due to its complex nature as well as its broad and indiscriminate effects, the current recession can be particularly devastating to many citizens. In attempting to alleviate the burden on the City of Charlotte, it is necessary to approach the issue from multiple perspectives.
    %ul
      %li <h4>Charitable Needs</h4>&nbsp;&nbsp;&nbsp;&nbsp;During the creation of The Corners Society in 2009, it was unanimously agreed upon that the present economic crisis and its direct impact on the citizens of Charlotte must be the focus of our immediate efforts. The “Great Recession” is a world wide issue, but its effects are most intensely felt at the community level. Charlotte is no exception.
      %li <h4>Volunteering</h4>&nbsp;&nbsp;&nbsp;&nbsp;By actually getting into the community and physically assisting Target Charities, The Corners Society helps to alleviate that over-stressed social infrastructure that frequently has limited personnel and financial resources.
      %li <h4>Investment in the Future</h4>&nbsp;&nbsp;&nbsp;&nbsp;The Corners Society invests in the future generations of Charlotte by contributing resources to Target Charities that focus on maintaining and improving the quality of life within the community.
      %li <h4>Direct Donation</h4>&nbsp;&nbsp;&nbsp;&nbsp;By giving money directly to our carefully selected Target Charities, The Corners Society is ensuring that our philanthropic efforts will have the greatest impact in the community and on those citizens over-burdened by the current economic hardship.
= render partial:"footer"